### ISSUE TITLE
Add Button Interactions

### ISSUE THREAD

**Issue by AnselemOdims** [oscafrica/osf-website#108]
So I went through the website and realized the buttons don't have any interaction states(hover, pressed, disabled, etc). It would look cooler(because its already cool) if simple animated interactions can be added.
I was wondering if this is something I can work on as my first open-source contribution.

**Comment by BolajiAyodeji** [comment]
Hi @AnselemOdims, thanks for submitting this issue!

We're working on a new design for the website. Can you check back when that is live to see if the buttons still need improvement and then you can work on it if we deem it fit?

Cheers!

**Comment by AnselemOdims** [comment]
Thanks for the reply @BolajiAyodeji,

It would be a pleasure to contribute in any way I can.

**Comment by BolajiAyodeji** [comment]
Hi @AnselemOdims, the new website is live now and you can pick up this task.

Here's the design of the components in [Figma](https://www.figma.com/file/IpD33qs3eaRznNKw2wWUQb/OSF-website(high-fidelity)?node-id=1215%3A4048). Kindly add the required hover interactions to the buttons across the website excluding the 2020 pages. Do let us know if you need any help; cheers!

**Comment by AnselemOdims** [comment]
Thank you so much for the opportunity @BolajiAyodeji. I just opened a PR for the change. Please let me know if any adjustments can be made or if there is any other way I can contribute.
