### ISSUE TITLE
Update the Homepage Design

### ISSUE THREAD

**Issue by Princesso** [oscafrica/osf-website#176]
Fix: The design for the homepage has been updated. See what it looked like [here](https://festival.oscafrica.org/). 
Find the new design [here](https://www.figma.com/file/uGbiNNx3nZqONJ7qBKORkG/website-%26-stage?node-id=291-2)

Guidelines: 
- In the repository, find the 2023 sub-folder in src. Please do not change files that are not related to this feature except when updating configurations or fixing a bug.
- In the components folder, find the 2023 sub-folder and create the components you will need for the home page.
- We use Tailwind CSS; kindly complete the designs with Tailwind only.
- Import the components where needed in the homepage file in the `pages` sub-folder of the 2023 folder.
- If possible, write tests; however, this should not hinder you from contributing as the team regularly updates tests.

Special Note: Take note of mobile designs. We prefer a mobile-first approach.

If you have any questions, ask @BolajiAyodeji or @Princesso

Thank you

**Comment by vimoppa** [comment]
Hi @Princesso, I am picking up this issue

**Comment by Princesso** [comment]
Thank you @vimoppa. I'll keep track of it here.

**Comment by Princesso** [comment]
Hi @vimoppa, how are you doing? Is there any update on this task?

**Comment by vimoppa** [comment]
@Princesso I just started work on this and will push an update today or tomorrow.

**Comment by Princesso** [comment]
Thank you @vimoppa. I'm looking forward to the updates.

**Comment by Princesso** [comment]
Hi @vimoppa how are you doing? Is there any update on this task? Should I reassign it?

**Comment by vimoppa** [comment]
Hi @Princesso, I'm still on this.
I will push common UI that would be used for the other pages.

Then after getting the new company logos and speakers' photos, I can complete the homepage.

So I would finish the homepage today and we can soft launch the Homepage and add the others by tomorrow or next.

**Comment by Princesso** [comment]
Hi @vimoppa good day. Thanks for the info. I didn't see any PRs though. 
Any updates? Thanks for your contribution.

**Comment by vimoppa** [comment]
Hi @Princesso, I wrote on the channel.
