### ISSUE TITLE
Create the Sustain Event Page

### ISSUE THREAD

**Issue by Princesso** [oscafrica/osf-website#178]
Feature: We need to design the sustain page.
Find the new design [here](https://www.figma.com/file/uGbiNNx3nZqONJ7qBKORkG/website-%26-stage?node-id=291-2)

Guidelines:

In the repository, find the 2023 sub-folder in src. Please do not change files that are not related to this feature except when updating configurations or fixing a bug.
In the components folder, find the 2023 sub-folder and create the components you will need for the sustain page.
We use Tailwind CSS; kindly complete the designs with Tailwind only.
Import the components where needed in the pages sub-folder of the 2023 folder.
If possible, write tests; however, this should not hinder you from contributing as the team regularly updates tests.
Special Note: Take note of mobile designs. We prefer a mobile-first approach.

If you have any questions, ask @BolajiAyodeji or @Princesso

Thank you

**Comment by vickywane** [comment]
Hi @Princesso, 

Can I take this up?

**Comment by Princesso** [comment]
Yes @vickywane . I'll assign it to you.
