### ISSUE TITLE
Create the Thank You Page

### ISSUE THREAD

**Issue by Princesso** [oscafrica/osf-website#180]
Feature: We need the `thank you` page created and designed. 
Find the design and assets [here](https://www.figma.com/file/uGbiNNx3nZqONJ7qBKORkG/website-%26-stage?node-id=291-2)

Guidelines: 
- In the repository, find the 2023 sub-folder in src. Please do not change files that are not related to this feature except when updating configurations or fixing a bug.
- In the components folder, find the 2023 sub-folder and create the components you will need for the thank you page.
- We use Tailwind CSS; kindly complete the designs with Tailwind only.
- Import the components where needed in the homepage file in the `pages` sub-folder of the 2023 folder.
- If possible, write tests; however, this should not hinder you from contributing as the team regularly updates tests.

Special Note: Take note of mobile designs. We prefer a mobile-first approach.

If you have any questions, ask @BolajiAyodeji or @Princesso

Thank you

**Comment by udokaokoye** [comment]
I tried creating the Thank You page but I checked the figma link but couldn't find a design for the Thank you page

**Comment by Princesso** [comment]
Hi @udokaokoye, thanks for your interest in contributing. I did check and the designs have been updated to exclude the thank you page. I'd go ahead to close this issue and reopen another one in accordance with the designs. In the meantime, you can pick another issue. Once again, thank you!
