### ISSUE TITLE
Add the FAQ page

### ISSUE THREAD

**Issue by Princesso** [oscafrica/osf-website#191]
Feature: We need to design the FAQ page.
Find the new design [here](https://www.figma.com/file/uGbiNNx3nZqONJ7qBKORkG/website-%26-stage?node-id=291-2)

Guidelines:

In the repository, find the 2023 sub-folder in src. Please do not change files unrelated to this feature except when updating configurations or fixing a bug.
In the components folder, find the 2023 sub-folder and create the components you will need for the FAQ page.
We use Tailwind CSS; kindly complete the designs with Tailwind only.
Import the components where needed in the pages sub-folder of the 2023 folder.
If possible, write tests; however, this should not hinder you from contributing as the team regularly updates tests.
Special Note: Take note of mobile designs. We prefer a mobile-first approach.

If you have any questions, ask @BolajiAyodeji or @Princesso

Thank you

**Comment by vickywane** [comment]
@Princesso @BolajiAyodeji Is there a document that contains the answers to the FAQs so I can add them?

**Comment by Princesso** [comment]
@vickywane you can just copy the answers from figma

**Comment by vickywane** [comment]
@Princesso The Figma board only shows the answer to question 1.

**Comment by Princesso** [comment]
https://festival.oscafrica.org/faqs
