### ISSUE TITLE
Fix travel page design

### ISSUE THREAD

**Issue by Princesso** [oscafrica/osf-website#193]
Hi @t-bello7, thanks again for your contribution.
Please can you look at the [sustain page](https://festival.oscafrica.org/2023/sustain-africa/) and reuse the styling there? The font and layout seem off by a few points. Thank you.

**Comment by t-bello7** [comment]
Okay @Princesso. I would work on improving the travel page. The background on the hero section of the sustain board is quite different from the design board. Do I need to change the background also to follow the sustain page 
![Screenshot_2023-06-06-19-23-32-697_com android chrome-edit](https://github.com/oscafrica/osf-website/assets/24270269/5405c0a3-cfa0-4099-b03f-419a70357f1d)

**Comment by Princesso** [comment]
@t-bello7 could you please use the background as it is on Figma? Thanks

**Comment by Princesso** [comment]
@t-bello7 Good evening and thank you so much for your contribution. Please can you update the travel page with the text in this [doc](https://docs.google.com/document/d/1suprM0H2hRC5nOaZFYrTpJDqnBnq63DSoprrUV9mGEQ/edit?usp=sharing)  instead?

**Comment by t-bello7** [comment]
@Princesso it is updated. Can you review the PR #201
