### ISSUE TITLE
Fix: Navbar Background Color Overflow

### ISSUE THREAD

**Issue by t-bello7** [oscafrica/osf-website#203]
# **🐞 Bug Report**

## **Describe the bug**

---
The navigation menu does not close back causing a black background over the image
### **To Reproduce**

1. Visit https://festival.oscafrica.org/
2. Ensure you are in desktop view
3. The background menu overflows

**Comment by Eazybee** [comment]
@Princesso  can I take this?

**Comment by Princesso** [comment]
@Eazybee yes please
