### ISSUE TITLE
Build the style guide (Components: Feedback)

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscafrica/osf-website#35]
The design team has built the Style guide, which can be found [here](https://www.figma.com/file/wtojDaoY2PJED946ZMIvsX/OSCA-style-guide%2Fpattern).

This issue is a chunk of #4, ensure to check it first.

- Build the Feedback component similar to the design and document all classes used
- Build with great focus on all states and responsiveness.

**Comment by ashinzekene** [comment]
What exactly is the feedback component?

**Comment by BolajiAyodeji** [comment]
> What exactly is the feedback component?

According to the style guide, it's the input field that returns either error or success but I think that component has been renamed on the design. 

![image](https://user-images.githubusercontent.com/30334776/71396649-444b9d00-261b-11ea-9bd9-bbf05b0550f3.png)

**Comment by ashinzekene** [comment]
I think it's just inputs with success and error states

**Comment by BolajiAyodeji** [comment]
> I think it's just inputs with success and error states

Yes, exactly.

**Comment by ashinzekene** [comment]
@BolajiAyodeji  Can you create issues for the remaining tasks so people interested can take them up

**Comment by BolajiAyodeji** [comment]
@ashinzekene Alright, I'll create some more.

**Comment by BolajiAyodeji** [comment]
> @ashinzekene Alright, I'll create some more.

For now, the remaining tasks are the open issues, every other thing is just adding contents and updating data which is pending from the other teams.

Let me know if you want to work on any other thing.
