### ISSUE TITLE
Build the style guide (Components)

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscafrica/osf-website#4]
The design team has built the Style guide, which can be found [here](https://www.figma.com/file/vO0aThJUcmB7VhsxW66q7h/Style-guide?node-id=4%3A98).
This style guide consists of `Typography` and `Components.`

Build a demo `components` page similar to the design and document all classes used in a `components.md` file

Build all components with great focus on all states, responsiveness, and experience as seen in the design. (The final component page should use the implementation in #13)

## Update

We have further broken this issue into smaller tasks for ease and efficiency; we now have 10 sub-issues for each component in this issue. You can pick one and ensure to use one component demo page for documentation and preview.
- #14: Button
- #15: Input Fields
- #16: Date Picker & Icons
- #17: Text Box & Pagination
- #18: Checkboxes
- #19: Radio Button
- #20: Selector
- #21: Text Link
- #22: Processing Options
- #23: Tab

![Components](https://user-images.githubusercontent.com/30334776/69572208-f152db80-0fc3-11ea-85e3-819004532fa3.png)

**Comment by BolajiOlajide** [comment]
@BolajiAyodeji What do you think about breaking down this ticket into smaller chunks? There are about more than 10 components here and this could lead to a huge chunk of dev work that could be split across other folks.

Let me know what you think.

**Comment by BolajiAyodeji** [comment]
> @BolajiAyodeji What do you think about breaking down this ticket into smaller chunks? There are about more than 10 components here and this could lead to a huge chunk of dev work that could be split across other folks.
> 
> Let me know what you think.

Yes, I was waiting to get comments, I was thinking of multiple people working on this ticket. We can split this into 10 issues with different levels based on its complexity, what do you think?

**Comment by BolajiOlajide** [comment]
Yes, folks might not be inclined to open an issue once it has been assigned because of the following reasons:

* they don't know it's a multiple assignees issue (since there's no way of showing that)
* they don't know the exact number of hands needed for this

Ultimately, whatever you decide is fine, however, I think breaking down this ticket will make it easy for every and anyone.

**Comment by BolajiAyodeji** [comment]
Yes, let's do it.

I'll split this ticket into smaller chunks with one issue for each component and reference this issue as a base. Works fine?

**Comment by BolajiOlajide** [comment]
You're the boss, boss. I'm here to serve. Assign me to the one for buttons. Thanks

**Comment by BolajiOlajide** [comment]
You know what's weird, getting an email from "Bolaji" saying "Bolaji" left a comment on an issue created by "Bolaji".

**Comment by BolajiAyodeji** [comment]
> You're the boss, boss. I'm here to serve. Assign me to the one for buttons. Thanks

Chief, we know the truth here :)

**Comment by BolajiAyodeji** [comment]
> You know what's weird, getting an email from "Bolaji" saying "Bolaji" left a comment on an issue created by "Bolaji".

Ahh :joy:
