### ISSUE TITLE
Test issues with Jest upgrade

### ISSUE THREAD

**Issue by BolajiAyodeji** [oscafrica/osf-website#96]
There seem to be test failing due to some issue with the Jest version `^27.1.0`. Can you help look into this @vimoppa, please?

**Comment by BolajiAyodeji** [comment]
Hi @vimoppa, can you take a look at this, please? The issue is still persistent. I was able to fix the first part but there still seems to be some conflicts with the newer version of Jest and other related packages.

If this is resolved, the current tests we have will have to change too since we have moved the previous conference pages and components to `/2020` and the current one will be `/` which would be `2022` by next year. I hope this is clear; do let me know if you have any questions chief.

This issue is open to anyone else too, please!

**Comment by usmahm** [comment]
I believe there'd still be some fixes needed to be done on this project, I messaged you concerning that but didn't get any response, however, I'd love to contribute if any fix whatsover comes up

Thanks @BolajiAyodeji

**Comment by BolajiAyodeji** [comment]
Hi @usmahm, do you want to work on this issue?

**Comment by BolajiAyodeji** [comment]
Any updates on this, please @vimoppa and @usmahm?
